# Generated by Django 5.2.12 on 2026-03-20 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('players', '0001_initial'),
        ('tryouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=20)),
                ('player_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_metrics', to='players.playerseason')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_metrics', to='tryouts.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoachRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank_order', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('coach_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='accounts.coachseason')),
                ('player_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_by', to='players.playerseason')),
            ],
            options={
                'ordering': ['rank_order'],
                'unique_together': {('coach_season', 'player_season')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scores', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('coach_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='accounts.coachseason')),
                ('player_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='players.playerseason')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tryouts.session')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='players.station')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('player_season', 'session', 'coach_season', 'station')},
            },
        ),
    ]
