# Generated by Django 5.2.12 on 2026-03-20 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('domain', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='leagues/logos/')),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('sportsconnect_report_url', models.URLField(blank=True)),
                ('sportsconnect_sync_interval_minutes', models.PositiveIntegerField(default=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('has_leagues', models.BooleanField(default=False, help_text='If true, this division splits into sub-leagues (e.g., American/National).')),
                ('league_names', models.JSONField(blank=True, default=list, help_text='Sub-league names, e.g. ["American", "National"].')),
                ('is_active', models.BooleanField(default=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='players.league')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sportsconnect_player_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.league')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('season_type', models.CharField(choices=[('spring', 'Spring'), ('fall', 'Fall'), ('summer', 'Summer')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('registration_open', models.BooleanField(default=False)),
                ('draft_complete', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='players.league')),
            ],
            options={
                'ordering': ['-year', 'season_type'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('eval_fields', models.JSONField(default=list, help_text='List of field definitions: [{key, label, type, min, max}, ...]')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='players.league')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='players.league')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_league', models.CharField(blank=True, max_length=50)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_seasons', to='players.division')),
                ('drafter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafting_for', to='accounts.coachseason')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_seasons', to='players.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='players.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_protected', models.BooleanField(default=False)),
                ('status', models.CharField(default='registered', max_length=20)),
                ('draft_slot', models.PositiveIntegerField(blank=True, null=True)),
                ('is_top_4', models.BooleanField(default=False)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('additional_email', models.EmailField(blank=True, max_length=254)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('sportsconnect_order_detail_id', models.CharField(blank=True, max_length=100)),
                ('rsvp_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('checkin_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('coaches_child_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches_children', to='accounts.coachseason')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_seasons', to='players.division')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_seasons', to='players.season')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='players.teamseason')),
            ],
            options={
                'ordering': ['player__last_name', 'player__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name', 'first_name'], name='players_pla_last_na_1786cf_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['sportsconnect_player_id'], name='players_pla_sportsc_909d6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamseason',
            unique_together={('team', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='playerseason',
            unique_together={('player', 'season')},
        ),
    ]
