# Generated by Django 5.1.15 on 2026-06-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="timezone",
            field=models.CharField(default="America/Los_Angeles", max_length=50),
        ),
    ]
