# Generated by Django 5.2.14 on 2026-06-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseason',
            name='balance_outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='playerseason',
            name='medical_form',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseason',
            name='photo_release',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
