# Generated by Django 5.0.3 on 2026-06-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_add_jersey_number'),
        ('players', '0002_playerseason_balance_outstanding_and_more'),
    ]

    operations = [
    ]
